import json
import streamlit as st
from agent.report_generator import render_report_html

# Page configuration
st.set_page_config(
    page_title="Vendor Compliance Report Viewer",
    page_icon="🛡️",
    layout="wide"
)

# Custom Title and CSS Styling
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap');
    html, body, [class*="css"], .stApp {
        font-family: 'Outfit', sans-serif;
    }
    /* Restrict app container width for readability and alignment */
    .block-container {
        max-width: 100% !important;
        padding-top: 2rem !important;
        padding-bottom: 3rem !important;
        padding-left: 2rem !important;
        padding-right: 2rem !important;
    }
</style>
""", unsafe_allow_html=True)

st.title("🛡️ Vendor Compliance Report Viewer")
st.markdown("Upload or paste a generated compliance JSON report to render it in detail.")

# Input layout: two column upload or paste option
col1, col2 = st.columns([1, 1])

uploaded_file = None
json_pasted = ""

with col1:
    st.subheader("Option 1: Upload JSON File")
    uploaded_file = st.file_uploader(
        "Upload compliance_report.json",
        type=["json"],
        help="Select the JSON report generated by the CLI compliance agent."
    )

with col2:
    st.subheader("Option 2: Paste JSON Text")
    json_pasted = st.text_area(
        "Paste JSON content here",
        height=180,
        placeholder='{"meta": {...}, "summary": {...}, ...}'
    )

# Determine the JSON input
report_data = None
parse_error = None

if uploaded_file is not None:
    try:
        report_data = json.load(uploaded_file)
    except Exception as e:
        parse_error = f"Error reading uploaded file: {e}"
elif json_pasted.strip() != "":
    try:
        report_data = json.loads(json_pasted)
    except Exception as e:
        parse_error = f"Error parsing pasted JSON: {e}"

# Render Report
if report_data is not None:
    st.success("JSON loaded successfully!")
    
    # Render the premium HTML dashboard
    try:
        html_report = render_report_html(report_data)
        st.markdown(html_report, unsafe_allow_html=True)
    except Exception as e:
        st.error(f"Error rendering compliance dashboard: {e}")
        st.info("The JSON format might be incomplete. See raw details below.")

    # Expandable raw data view
    with st.expander("⚙️ View Raw JSON Data Structure", expanded=False):
        st.json(report_data)

elif parse_error is not None:
    st.error(parse_error)
else:
    st.info("Please upload a file or paste JSON content to view the compliance analysis.")
